### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LinkOut** [Manabu-GT/ExpandableTextView#10]
java.lang.NullPointerException
	at com.ms.square.android.expandabletextview.ExpandableTextView.findViews(ExpandableTextView.java:226)
	at com.ms.square.android.expandabletextview.ExpandableTextView.onFinishInflate(ExpandableTextView.java:151)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:814)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:400)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:332)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:688)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:677)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:677)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:815)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:646)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:589)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:584)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This error, im using Android Studio & Gradle.

    compile 'com.ms-square:expandableTextView:0.1.3'

**Comment by Fgabz** [comment]
Same for me

**Comment by Manabu-GT** [comment]
The currently implementation requires that the view Ids for TextView and ImageButton to be set to "@id/expandable_text" and "@id/expand_collapse" respectively.
I also updated README to mention about it.

If the problem still persists after you update your layout file to use those ids just like the below, please let me know and I will investigate.

  
  <com.ms.square.android.expandabletextview.ExpandableTextView
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:expandableTextView="http://schemas.android.com/apk/res-auto"
      android:id="@+id/expand_text_view"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:orientation="vertical"
      expandableTextView:maxCollapsedLines="4"
      expandableTextView:animDuration="200">
      <TextView
          android:id="@id/expandable_text"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_marginLeft="10dp"
          android:layout_marginRight="10dp"
          android:textSize="16sp"
          android:textColor="#666666" />
      <ImageButton
          android:id="@id/expand_collapse"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:layout_margin="16dp"
          android:layout_gravity="right|bottom"
          android:background="@android:color/transparent"/>
  </com.ms.square.android.expandabletextview.ExpandableTextView>

**Comment by LinkOut** [comment]
Ok i got it. Working Thanks.

**Comment by LinkOut** [comment]
Is it possible to use a ImageView with the same id as the ImageButton? Is there a way to customize the imageButton image? Thanks.

**Comment by Manabu-GT** [comment]
Is it possible to use a ImageView with the same id as the ImageButton?
-> Nope. It currently only supports ImageButton.

Is there a way to customize the imageButton image? 
->As written on README, you can set the following attributes in your layout xml file to customize the images of the ImageButton.

 * `expandDrawable`
 Customize a drawable set to ImageButton to expand the TextView

 * `collapseDrawable`
 Customize a drawable set to ImageButton to collapse the TextView

Thanks and plz let me know if you have any other issue.

**Comment by LinkOut** [comment]
expandableTextView:expandDrawable="@drawable/ic_my_draw" seems not to works. Is it correct? Inside the ImageButton.

**Comment by LinkOut** [comment]
You've done a great job, works perfectly. Thank You.

**Comment by davern97** [comment]
I have a problem:
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ms.square.android.expandabletextview.ExpandableTextView.setText(java.lang.CharSequence)' on a null object reference
                      at com.company.jobs.jobsproject.MainActivity.onCreate(MainActivity.java:39)

In the MainActivity I have this:
        expTv1 = (ExpandableTextView) findViewById(R.id.expand_text_view);
        expTv1.setText(texto_largo); //line 39

texto_largo is a String with the "Lorem Ipsum"
